In [9]:
#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
# Parameters, first_5 is a list containing first 5 words
string = "The fist is in a".upper()
first_5 = string.split(" ")

In [4]:
from keras.models import load_model
from keras.utils import to_categorical
import numpy as np
from function1 import *

# Loading the Dictionary
with open("import/dictionary.txt","r",encoding="utf8") as file:
    dictionary = [string.replace("\n","") for string in file.readlines()]

In [21]:
# The list containing all the words, generated words will be appended to this list
words = []
words.extend(first_5)

In [16]:
# Getting indexes of the words
first_5 = [[dictionary.index(word)] for word in first_5]
# Converting it to categorical
categorical = to_categorical(first_5,num_classes=len(dictionary)+1,dtype="byte")

print(first_5)
print(categorical)
print(np.shape(categorical))

[[2533], [763], [5152], [852], [757]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(5, 7338)


In [9]:
# Loading the model
from keras.optimizers import Adagrad

model = load_model("models/Dense_70epochs.h5",compile=False)
opt = Adagrad(learning_rate = 0.01)
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])

In [17]:
def predict_a_word(inputs):
  """
  This model predicts a word according to the inputs
  Inputs is a list and it contains 5 strings
  """
  # Converting Strings to Categorical
  window = inputs.copy()
  window = [[dictionary.index(word)] for word in window]
  categorical = to_categorical(window,num_classes=len(dictionary)+1,dtype="byte")

  # Predicting
  categorical = np.reshape(categorical,(1, 5, 7338, 1))
  pred = model.predict(categorical)
  pred = np.reshape(pred,(7338,1))
  pred = toInt(pred)

  # Getting the predicted words, which is only 1 word
  # The code was changed to see multiple outputs during the test
  # But this code works for 1 word also
  ones = []
  for i,j in enumerate(pred.tolist()):
    if j == 1:
      ones.append(i)
  new_words = [dictionary[ones[i]] for i in range(len(ones))]
  return new_words[0]

In [22]:
# Getting the predicted long string
length = 100
for i in range(length):
  print(i)
  input = words[-5:]
  new_word = predict_a_word(input)
  words.append(new_word)

# Getting the output
print(" ".join(words))

0
1/1 [==============================] - 0s 78ms/step
1
1/1 [==============================] - 0s 61ms/step
2
1/1 [==============================] - 0s 58ms/step
3
1/1 [==============================] - 0s 59ms/step
4
1/1 [==============================] - 0s 58ms/step
5
1/1 [==============================] - 0s 58ms/step
6
1/1 [==============================] - 0s 57ms/step
7
1/1 [==============================] - 0s 56ms/step
8
1/1 [==============================] - 0s 56ms/step
9
1/1 [==============================] - 0s 58ms/step
10
1/1 [==============================] - 0s 60ms/step
11
1/1 [==============================] - 0s 60ms/step
12
1/1 [==============================] - 0s 62ms/step
13
1/1 [==============================] - 0s 60ms/step
14
1/1 [==============================] - 0s 61ms/step
15
1/1 [==============================] - 0s 93ms/step
16
1/1 [==============================] - 0s 61ms/step
17
1/1 [==============================] - 0s 59ms/step
18
1/1 [============

In [23]:
" ".join(words).capitalize()

'The fist is in a reese is no one by the the of the deakins is a and hale is going to be i know you and reese i sarah sarah i want you to see me jack if we were a bus jack looks up to jack i was a little tyler is tyler this i tyler you jack i could be you think of the jack i tyler i want to know tyler i want to know tyler i want to know tyler i want to know tyler i want to know tyler i want to know tyler i want to know tyler'